# Generated by Django 4.2 on 2023-06-01 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abyss_randomizer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='uid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
